-- MIGRATION 0001 REMOVED
-- This file previously created workspaces, posts, and analytics_snapshots
-- with an old schema (owner_email TEXT UNIQUE NOT NULL) that conflicts with
-- all migrations from 0010 onward.
-- Superseded by: schema_final.sql
-- Do not execute. Left as a tombstone to preserve migration numbering.
