import type { CarouselTheme } from "@/types/carousel"

export const CAROUSEL_THEMES: CarouselTheme[] = [
  {
    id: "professional-blue",
    name: "Professional Blue",
    colors: {
      primary: "#1e40af",
      secondary: "#3b82f6",
      accent: "#93c5fd",
      background: "#eff6ff",
      text: "#1e3a5f",
      textMuted: "#64748b",
    },
    fonts: { heading: "font-jakarta", body: "font-jakarta" },
    patterns: ["pattern-dots-blue", "pattern-grid-light"],
    gradient: "linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)",
  },
  {
    id: "bold-red",
    name: "Bold Red",
    colors: {
      primary: "#dc2626",
      secondary: "#ef4444",
      accent: "#fca5a5",
      background: "#fff1f2",
      text: "#7f1d1d",
      textMuted: "#6b7280",
    },
    fonts: { heading: "font-jakarta", body: "font-jakarta" },
    patterns: ["pattern-diagonal-red", "pattern-noise"],
    gradient: "linear-gradient(135deg, #fff1f2 0%, #fee2e2 100%)",
  },
  {
    id: "calm-green",
    name: "Calm Green",
    colors: {
      primary: "#059669",
      secondary: "#10b981",
      accent: "#6ee7b7",
      background: "#ecfdf5",
      text: "#064e3b",
      textMuted: "#6b7280",
    },
    fonts: { heading: "font-jakarta", body: "font-cormorant" },
    patterns: ["pattern-leaves", "pattern-wave-green"],
    gradient: "linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%)",
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    colors: {
      primary: "#b45309",
      secondary: "#d97706",
      accent: "#fbbf24",
      background: "#fffbeb",
      text: "#78350f",
      textMuted: "#92400e",
    },
    fonts: { heading: "font-cormorant", body: "font-jakarta" },
    patterns: ["pattern-hexagon-gold", "pattern-linen"],
    gradient: "linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)",
  },
  {
    id: "midnight-dark",
    name: "Midnight Dark",
    colors: {
      primary: "#818cf8",
      secondary: "#6366f1",
      accent: "#c7d2fe",
      background: "#0f172a",
      text: "#f1f5f9",
      textMuted: "#94a3b8",
    },
    fonts: { heading: "font-jakarta", body: "font-jakarta" },
    patterns: ["pattern-circuit", "pattern-stars"],
    gradient: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)",
  },
  {
    id: "teal-authority",
    name: "Teal Authority",
    colors: {
      primary: "#0d4a45",
      secondary: "#0f766e",
      accent: "#5eead4",
      background: "#f0fdfa",
      text: "#0d4a45",
      textMuted: "#6b7280",
    },
    fonts: { heading: "font-jakarta", body: "font-jakarta" },
    patterns: ["pattern-wave-teal", "pattern-dots-teal"],
    gradient: "linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%)",
  },
  {
    id: "rose-soft",
    name: "Rose Soft",
    colors: {
      primary: "#be185d",
      secondary: "#ec4899",
      accent: "#fbcfe8",
      background: "#fdf2f8",
      text: "#831843",
      textMuted: "#9d174d",
    },
    fonts: { heading: "font-cormorant", body: "font-jakarta" },
    patterns: ["pattern-floral", "pattern-soft-dots"],
    gradient: "linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)",
  },
  {
    id: "slate-minimal",
    name: "Slate Minimal",
    colors: {
      primary: "#334155",
      secondary: "#475569",
      accent: "#94a3b8",
      background: "#f8fafc",
      text: "#0f172a",
      textMuted: "#475569",
    },
    fonts: { heading: "font-jakarta", body: "font-jakarta" },
    patterns: ["pattern-clean", "pattern-thin-grid"],
    gradient: "linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)",
  },
  {
    id: "orange-energy",
    name: "Orange Energy",
    colors: {
      primary: "#c2410c",
      secondary: "#ea580c",
      accent: "#fed7aa",
      background: "#fff7ed",
      text: "#7c2d12",
      textMuted: "#92400e",
    },
    fonts: { heading: "font-jakarta", body: "font-jakarta" },
    patterns: ["pattern-burst", "pattern-warm-dots"],
    gradient: "linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%)",
  },
  {
    id: "purple-creative",
    name: "Purple Creative",
    colors: {
      primary: "#7c3aed",
      secondary: "#8b5cf6",
      accent: "#c4b5fd",
      background: "#faf5ff",
      text: "#4c1d95",
      textMuted: "#6d28d9",
    },
    fonts: { heading: "font-jakarta", body: "font-jakarta" },
    patterns: ["pattern-abstract", "pattern-geometric"],
    gradient: "linear-gradient(135deg, #faf5ff 0%, #ede9fe 100%)",
  },
]

export const getThemeById = (id: string): CarouselTheme =>
  CAROUSEL_THEMES.find((t) => t.id === id) ?? CAROUSEL_THEMES[0]

export const DEFAULT_THEME_ID = "teal-authority"
