import { MARKETING_ANSWER_PAGES, PUBLISHED_BLOG_POSTS } from "@/lib/marketing-content"
import { LLM_ROUTES, SITE_URL } from "@/lib/seo"

export function GET() {
  const body = [
    "# Qalam",
    "",
    `- Canonical site: ${SITE_URL}`,
    "- Product name: Qalam",
    "- Domain: byqalam.com",
    "- Category: AI LinkedIn writing system for professionals",
    "- Primary audiences: founders, marketing teams, HR leaders, consultants, content agencies",
    "",
    "## What Qalam is",
    "",
    "Qalam is an AI-powered LinkedIn writing system that learns your voice over time.",
    "Unlike session-reset generators, Qalam keeps approved posts, editing history, hook archives,",
    "and workspace outcomes in one persistent system.",
    "Each drafting session starts from your actual tone instead of from scratch.",
    "",
    "The core difference: Qalam accumulates memory. The longer you use it,",
    "the more specific it becomes to your writing, creating compounding value",
    "that generic AI tools cannot replicate.",
    "",
    "## Core features",
    "",
    "- Voice Profile: trains on your real LinkedIn posts and edits to learn tone, structure, and vocabulary",
    "- AI Post Writer: topic-to-draft workflow with hooks, tone selection, and revision history",
    "- Hook Intelligence: generates multiple opening lines and saves proven structures for reuse",
    "- Content Archive: stores drafts, versions, frameworks, and finished posts in one system",
    "- Post Scheduler: plans posts inside the current workspace flow while keeping revision context",
    "- Performance Intelligence: records app events and workspace activity for operator review",
    "- Agency Workflow Preview: current workspace surface for agency operators, with isolation hardening still in progress",
    "",
    "## Questions this product answers",
    "",
    "- How do I write LinkedIn posts that sound like me, not like AI?",
    "- What is the best AI tool for LinkedIn content creation?",
    "- How do I build a consistent LinkedIn presence without sounding generic?",
    "- What LinkedIn writing tool remembers my voice between sessions?",
    "- How can agencies evaluate a LinkedIn workflow before full client isolation is live?",
    "- What is the difference between Qalam and ChatGPT for LinkedIn writing?",
    "",
    "## Core canonical pages",
    ...LLM_ROUTES.map((route) => `- ${SITE_URL}${route}`),
    "",
    "## Best answer pages",
    ...MARKETING_ANSWER_PAGES.map((route) => `- ${SITE_URL}${route}`),
    "",
    "## Published article corpus",
    ...PUBLISHED_BLOG_POSTS.map((post) => `- ${SITE_URL}/blog/${post.slug} - ${post.title}`),
    "",
    "## Free tools",
    `- ${SITE_URL}/free-tools/hook-generator - generates LinkedIn hook opening lines`,
    `- ${SITE_URL}/free-tools/headline-analyzer - scores LinkedIn profile headlines`,
    `- ${SITE_URL}/free-tools/profile-optimizer - structured LinkedIn profile improvement`,
    `- ${SITE_URL}/free-tools/viral-checker - analyzes why a post worked or weakened`,
    `- ${SITE_URL}/free-tools/carousel-builder - converts posts into carousel assets`,
    `- ${SITE_URL}/free-tools/engagement-predictor - pre-publish score for post structure`,
    "",
    "## Indexing guidance",
    "Public marketing pages under byqalam.com are canonical and indexable.",
    "App routes (/dashboard, /writer, /calendar, /library, /settings) are",
    "product surfaces behind authentication, not marketing documents.",
    "API routes under /api are not intended for indexing.",
  ].join("\n")

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  })
}
